name: Zwei Vanilla Desktop
id: zwei
vibversion: 1.0.7

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  addincludes: true
  singlelayer: false
  labels:
    maintainer: self-maintained
  args:
    DEBIAN_FRONTEND: noninteractive

  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:

  - name: init-setup
    type: shell
    commands:
      - lpkg --unlock
      - apt-get update

  - name: install-sunshine
    type: shell
    commands:
      - dnf -y copr enable lizardbyte/stable
      - dnf -y install sunshine --setopt=install_weak_deps=False
      - dnf clean all

  - name: example-commands
    type: shell
    commands:
      - echo Example output

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
      - apt-get autoremove -y
      - apt-get clean
      - lpkg --lock

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*